name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # uses GitHub's checkout action to checkout code form the release branch
      - name: Checkout code
        uses: actions/checkout@v6.0.0

      # sets up .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v5.0.0
        with:
          global-json-file: ./global.json

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./AdventOfCode

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./AdventOfCode

      - name: Run tests
        run: dotnet test --configuration Release --no-build
        working-directory: ./AdventOfCode

      - name: Solve all
        run: dotnet run -c Release --no-build -- all
        working-directory: ./AdventOfCode
